{{- if .Values.env.CLAMAV_ENABLED }}
{{- if ne .Values.environment "local" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clamavdb-nfs-server
  namespace: {{ .Values.namespace | default "dsgov" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "nfs-server"
  template:
    metadata:
      labels:
        app: "nfs-server"
    spec:
      containers:
      - name: clamavdb-nfs-server
        image: "{{ .Values.clamav.nfsServer.image.repository }}:{{ .Values.clamav.nfsServer.image.tag }}"
        imagePullPolicy: "{{ .Values.clamav.nfsServer.image.pullPolicy}}"
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: clamdb-storage
      volumes:
        - name: clamdb-storage
          persistentVolumeClaim:
            claimName: clamavdb-claim
---
apiVersion: v1
kind: Service
metadata:
  name: clamavdb-nfs-server
  namespace: {{ .Values.namespace | default "dsgov" }}
spec:
  selector:
    app: "nfs-server"
  ports:
    - name: nfs
      protocol: TCP
      port: 2049
      targetPort: nfs
    - name: mountd
      protocol: TCP
      port: 20048
      targetPort: mountd
    - name: rpcbind
      protocol: TCP
      port: 111
      targetPort: rpcbind
{{- end }}
{{- end }}
