environment: "local"

postgres:
  enabled: false
  persistence:
    size: 1Gi
  env:
    POSTGRES_DB: "local-document-management-db"
    POSTGRES_HOST: 'postgres-14-alpine'
    POSTGRES_PASSWORD: "root"
    POSTGRES_PORT: 5432
    POSTGRES_USER: "root"

resources:
  documentManagement:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 1024Mi
  cerbos:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 256Mi
  clamavService:
    requests:
      cpu: 100m
      memory: 2Gi
    limits:
      memory: 2Gi
  clamavMirror:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 256Mi
  pubSubEmulator:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi
  gcloudStorageEmulator:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 256Mi

gcloudStorageEmulator:
  persistent: false
  persistentStorage:
    className: "gcloud-storage-emulator"
    size: 2Gi
    nodePath: "/mnt/gcloud-storage-emulator"

clamav:
  persistentStorage:
    size: 2Gi

net:
  host: "api.cwb07.test"

env:
  # start infrastructure selector configs
  CLAMAV_ENABLED: true
  DOCUMENT_PROCESSING_ENABLED: true
  GOOGLE_STORAGE_EMULATED: true
  PUBSUB_EMULATOR_HOST: "pubsub-emulator-service:8085" # set actual "host:port" to enable or false to disable
  PUBSUB_EMULATOR_ENABLED: true
  # cwb07-events publisher topics separated by comma
  PUBLISHER_TOPICS: projects/cwb07-dev-ac55/topics/APPLICATION_ROLE_REPORTING
  DOCUMENT_QUALITY_PROCESSOR_ID: "fdb5cf560a684afa"
  DOCUMENT_ID_PROOFING_PROCESSOR_ID: "e2e0b9bcf0d940dd"
  # end of infrastructure selector configs
  ALLOWED_ORIGINS: "http://localhost:4200, http://localhost:4201, http://agency.cwb07.test, http://public.cwb07.test, http://employer.cwb07.test"
  DB_CONNECTION_URL: "jdbc:postgresql://document-management-postgres:5432/local-document-management-db"
  DB_USERNAME: "root"
  DB_PASSWORD: "root"
  GCP_PROJECT_ID: "cwb07-dev-ac55"
  CERBOS_URI: "127.0.0.1:3592"
  SELF_SIGN_PUBLIC_KEY: "${sm://projects/cwb07-dev-ac55/secrets/cwb07-self-signed-token-public-key/versions/latest}"
  SELF_SIGN_PRIVATE_KEY: "${sm://projects/cwb07-dev-ac55/secrets/cwb07-self-signed-token-private-key/versions/latest}"
  USER_MANAGEMENT_BASE_URL: "http://user-management/um"
  PUBSUB_CLAMAV_TOPIC: "projects/cwb07-dev-ac55/topics/NEW_FILE_UPLOAD"
  PUBSUB_DOCUMENT_PROCESSING_TOPIC: "projects/cwb07-dev-ac55/topics/DOCUMENT_PROCESSING_REQUESTS"
  PUBSUB_DOCUMENT_PROCESSING_RESULT_TOPIC: "projects/cwb07-dev-ac55/topics/DOCUMENT_PROCESSING_RESULTS"
  PUBSUB_CLAMAV_SUBSCRIPTION: "projects/cwb07-dev-ac55/subscriptions/NEW_FILE_UPLOAD_SUBSCRIPTION"
  PUBSUB_DOCUMENT_PROCESSING_SUBSCRIPTION: "projects/cwb07-dev-ac55/subscriptions/DOCUMENT_PROCESSING_SUBSCRIPTION"
  PUBSUB_DOCUMENT_PROCESSING_RESULT_DEAD_LETTER_TOPIC: "projects/cwb07-dev-ac55/topics/DOCUMENT_PROCESSING_DEAD_LETTER"
  EVENTS_DOCUMENT_PROCESSING_TOPIC: "projects/cwb07-dev-ac55/topics/DOCUMENT_PROCESSING_INITIATION"
  EVENTS_DOCUMENT_PROCESSING_SUBSCRIPTION: "projects/cwb07-dev-ac55/subscriptions/DOCUMENT_PROCESSING_INITIATION_SUBSCRIPTION"
  UNSCANNED_BUCKET_NAME: cwb07-dev-unscanned
  QUARANTINED_BUCKET_NAME: cwb07-dev-quarantined
  SCANNED_BUCKET_NAME: cwb07-dev-scanned
  STORAGE_PROVIDER: "google"
  GCLOUD_STORAGE_EMULATOR_HOST: "gcloud-storage-emulator-service:4443"
  ALLOWED_MIME_TYPES:
    - "image/gif"
    - "image/jpeg"
    - "image/png"
    - "image/heic"
    - "application/pdf"
    - "text/csv"
    - "application/msword"
    - "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    - "application/rtf"
    - "text/plain"
    - "application/vnd.ms-excel"
    - "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    - "application/vnd.ms-xpsdocument"
    - "application/vnd.wordperfect"
    - "application/vnd.oasis.opendocument.text"
    - "image/svg+xml"
    - "image/tiff"
  ALLOWED_OCTET_STREAM_EXTENSIONS:
    - ".mpa"
  TOKEN_PRIVATE_KEY_SECRET: "cwb07-self-signed-token-private-key"
  TOKEN_ISSUER: "cwb07"
  TOKEN_PRIVATE_KEY_VERSION: "latest"
  OTEL_SAMPLER_PROBABILITY: 1.0 # valid values: [0.0 - 1.0]